export type BillingErrorCode =
  | "AMOUNT_INVALID"
  | "QUANTITY_INVALID"
  | "UNIT_AMOUNT_INVALID"
  | "DISCOUNT_BPS_INVALID"
  | "TAX_BPS_INVALID"
  | "DESCRIPTION_REQUIRED"
  | "MONEY_OVERFLOW"
  | "INVOICE_TOTAL_INVALID"
  | "PAYMENT_EXCEEDS_BALANCE"
  | "CREDIT_EXCEEDS_REMAINING"
  | "REFUND_EXCEEDS_AVAILABLE"
  | "IDEMPOTENCY_KEY_REQUIRED"
  | "IDEMPOTENCY_KEY_CONFLICT"
  | "INVOICE_NOT_FOUND"
  | "INVOICE_NOT_DRAFT"
  | "INVOICE_NOT_ISSUED"
  | "INVOICE_VOID_NOT_ALLOWED"
  | "PAYMENT_NOT_FOUND"
  | "PAYMENT_NOT_COMPLETED"
  | "PAYMENT_HAS_COMPLETED_REFUNDS"
  | "PAYMENT_METHOD_INVALID"
  | "REFUND_NOT_FOUND"
  | "REFUND_NOT_COMPLETED"
  | "OWNER_NOT_FOUND"
  | "PATIENT_NOT_FOUND"
  | "PATIENT_OWNER_MISMATCH"
  | "APPOINTMENT_NOT_FOUND"
  | "APPOINTMENT_OWNER_MISMATCH"
  | "APPOINTMENT_PATIENT_MISMATCH"
  | "CLINIC_SNAPSHOT_INVALID"
  | "DATE_INVALID";

export class BillingDomainError extends Error {
  readonly code: BillingErrorCode;

  constructor(code: BillingErrorCode, message: string) {
    super(message);
    this.name = "BillingDomainError";
    this.code = code;
  }
}
